### ISSUE TITLE
Add Circle CI

### ISSUE THREAD

**Issue by camirmas** [msmykowski/enqueue#2]
🔥🔥🔥🔥🔥🔥 

We plan to use Circle CI. Set up to run on any PRs into master.

https://circleci.com/

**Comment by msmykowski** [comment]
Need to look into NPM test.  Some set up needs to be done to get gulp to run correctly on circle.

```
[03:30:48] Using gulpfile ~/enqueue/gulpfile.js
[03:30:48] Starting 'lint'...
[03:30:51] Finished 'lint' after 2.89 s
[03:31:02] Using gulpfile ~/enqueue/gulpfile.js
[03:31:02] Starting 'spec-app'...
[03:31:09] Plumber found unhandled error:
 Error in plugin 'webpack-stream'
Message:
    ./app/bootstrap.js
Module not found: Error: Cannot resolve module 'css' in /home/ubuntu/enqueue/app
resolve module css in /home/ubuntu/enqueue/app
  looking for modules in /home/ubuntu/enqueue/node_modules
    module variation css-webpack-loader
      /home/ubuntu/enqueue/node_modules/css-webpack-loader doesn't exist (module as directory)
      resolve 'file' css-webpack-loader in /home/ubuntu/enqueue/node_modules
        resolve file
          /home/ubuntu/enqueue/node_modules/css-webpack-loader doesn't exist
          /home/ubuntu/enqueue/node_modules/css-webpack-loader.webpack-loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css-webpack-loader.web-loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css-webpack-loader.loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css-webpack-loader.js doesn't exist
    module variation css-web-loader
      /home/ubuntu/enqueue/node_modules/css-web-loader doesn't exist (module as directory)
      resolve 'file' css-web-loader in /home/ubuntu/enqueue/node_modules
        resolve file
          /home/ubuntu/enqueue/node_modules/css-web-loader doesn't exist
          /home/ubuntu/enqueue/node_modules/css-web-loader.webpack-loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css-web-loader.web-loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css-web-loader.loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css-web-loader.js doesn't exist
    module variation css-loader
      /home/ubuntu/enqueue/node_modules/css-loader doesn't exist (module as directory)
      resolve 'file' css-loader in /home/ubuntu/enqueue/node_modules
        resolve file
          /home/ubuntu/enqueue/node_modules/css-loader doesn't exist
          /home/ubuntu/enqueue/node_modules/css-loader.webpack-loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css-loader.web-loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css-loader.loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css-loader.js doesn't exist
    module variation css
      /home/ubuntu/enqueue/node_modules/css doesn't exist (module as directory)
      resolve 'file' css in /home/ubuntu/enqueue/node_modules
        resolve file
          /home/ubuntu/enqueue/node_modules/css doesn't exist
          /home/ubuntu/enqueue/node_modules/css.webpack-loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css.web-loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css.loader.js doesn't exist
          /home/ubuntu/enqueue/node_modules/css.js doesn't exist
[/home/ubuntu/enqueue/node_modules/css-webpack-loader]
[/home/ubuntu/enqueue/node_modules/css-webpack-loader]
[/home/ubuntu/enqueue/node_modules/css-webpack-loader.webpack-loader.js]
[/home/ubuntu/enqueue/node_modules/css-webpack-loader.web-loader.js]
[/home/ubuntu/enqueue/node_modules/css-webpack-loader.loader.js]
[/home/ubuntu/enqueue/node_modules/css-webpack-loader.js]
[/home/ubuntu/enqueue/node_modules/css-web-loader]
[/home/ubuntu/enqueue/node_modules/css-web-loader]
[/home/ubuntu/enqueue/node_modules/css-web-loader.webpack-loader.js]
[/home/ubuntu/enqueue/node_modules/css-web-loader.web-loader.js]
[/home/ubuntu/enqueue/node_modules/css-web-loader.loader.js]
[/home/ubuntu/enqueue/node_modules/css-web-loader.js]
[/home/ubuntu/enqueue/node_modules/css-loader]
[/home/ubuntu/enqueue/node_modules/css-loader]
[/home/ubuntu/enqueue/node_modules/css-loader.webpack-loader.js]
[/home/ubuntu/enqueue/node_modules/css-loader.web-loader.js]
[/home/ubuntu/enqueue/node_modules/css-loader.loader.js]
[/home/ubuntu/enqueue/node_modules/css-loader.js]
[/home/ubuntu/enqueue/node_modules/css]
[/home/ubuntu/enqueue/node_modules/css]
[/home/ubuntu/enqueue/node_modules/css.webpack-loader.js]
[/home/ubuntu/enqueue/node_modules/css.web-loader.js]
[/home/ubuntu/enqueue/node_modules/css.loader.js]
[/home/ubuntu/enqueue/node_modules/css.js]
 @ ./app/bootstrap.js 13:4-45
[03:31:09] Jasmine server listening on port 8000

No specs found
Finished in 0 seconds
[03:31:09] Finished 'spec-app' after 6.89 s
[03:31:20] Using gulpfile ~/enqueue/gulpfile.js
[03:31:20] Starting 'spec-server'...
FF

Failures: 
1) PlaylistRouter GET /playlist/:id returns status code 200
1.1) Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at [object Object]._onTimeout (/home/ubuntu/enqueue/node_modules/gulp-jasmine/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1909:23)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

2) UserRouter GET /user/:id returns status code 200
2.1) Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at [object Object]._onTimeout (/home/ubuntu/enqueue/node_modules/gulp-jasmine/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1909:23)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

2 specs, 2 failures
Finished in 10 seconds
[03:31:30] Plumber found unhandled error:
 Error in plugin 'gulp-jasmine'
Message:
    Tests failed
```

These are not legitimate failures.
